(defun sample(first_lst second_lst a)
  (print " Trying cons: " )
  (terpri)
  (write (cons a first_lst))
  (terpri)
  (write(cons first_lst second_lst))
  (terpri)
  (print "Trying append: ")
  (terpri)
  (write (append (list a) first_lst))
  (terpri)
  (write (append first_lst (list a)))
  (terpri)
  (write (append first_lst second_lst))
  (terpri)
  (print "Trying list: ")
  (terpri)
  (write (list a first_lst))
  (terpri)
  (write (list first_lst second_lst))
)
