 
; -------------------------------------------------------------------
;
; Database Management
;
; -------------------------------------------------------------------

(defun database-setup ()
  (defun assign-properties (dis-list carrier-list)
    (cond((and(null dis-list)(null carrier-list)) nil)
           ((and dis-list carrier-list)
              (setf (get (intern(caar dis-list)) 'distance) 
                    (cons (cdar dis-list)
                          (get (intern(caar dis-list)) 'distance)))
              (setf (get (intern(cadar dis-list)) 'distance) 
                    (cons (cons (caar dis-list) (cddar dis-list))
                          (get (intern(cadar dis-list)) 'distance)))
              (setf (get(intern(cadar carrier-list))(caar carrier-list))
                    (cons (caddar carrier-list)
                          (get (intern(cadar carrier-list))
                               (caar carrier-list))))
              (assign-properties (cdr dis-list)(cdr carrier-list)))
           ((null carrier-list)
              (setf (get (intern(caar dis-list)) 'distance) 
                    (cons (cdar dis-list)
                          (get (intern(caar dis-list)) 'distance)))
              (setf (get (intern(cadar dis-list)) 'distance) 
                    (cons (cons (caar dis-list) (cddar dis-list))
                          (get (intern(cadar dis-list)) 'distance)))
              (assign-properties (cdr dis-list) nil))
           (t
              (setf (get (intern(cadar carrier-list))(caar carrier-list))
                    (cons(caddar carrier-list)
                         (get (intern(cadar carrier-list)) 
                              (caar carrier-list))))
              (assign-properties nil (cdr carrier-list)))))
            
  (let((distance
         '(
           ("ithaca" "pittsburgh" 365)
           ("ithaca" "bangor" 673)
           ("ithaca" "losangeles" 3730 )
           ("ithaca" "memphis" 1423)
           ("ithaca" "baltimore" 350)
           ("ithaca" "denver" 2398)
           ("ithaca" "miami" 1887)
           ("ithaca" "stlouis" 1239)
           ("ithaca" "newark" 270)
           ("ithaca" "boston" 446)
           ("ithaca" "philadelphia" 299)
           ("ithaca" "westpalm" 1779) 
           ("ithaca" "roanoke" 644)            
           ("bangor" "pittsburgh" 1050)
           ("bangor" "losangeles" 4347 )
           ("bangor" "memphis" 2095)
           ("bangor" "baltimore" 893)
           ("bangor" "denver" 3007)
           ("bangor" "miami" 2357)
           ("bangor" "stlouis" 1905)
           ("bangor" "newark" 632)
           ("bangor" "boston" 350)
           ("bangor" "philadelphia" 757)
           ("bangor" "westpalm" 2253) 
           ("bangor" "roanoke" 1254) 
           ("pittsburgh" "losangeles" 3439)
           ("pittsburgh" "memphis" 1059)
           ("pittsburgh" "baltimore" 312)
           ("pittsburgh" "denver" 2125)
           ("pittsburgh" "miami" 1634)
           ("pittsburgh" "stlouis" 906)
           ("pittsburgh" "newark" 400)
           ("pittsburgh" "boston" 800)
           ("pittsburgh" "philadelphia" 100)
           ("pittsburgh" "westpalm" 1500) 
           ("pittsburgh" "roanoke" 350) 
           ("losangeles" "memphis" 2586)
           ("losangeles" "baltimore" 3730)
           ("losangeles" "denver" 1340)
           ("losangeles" "miami" 3758)
           ("losangeles" "stlouis" 2551)
           ("losangeles" "newark" 3927)
           ("losangeles" "boston" 4176)
           ("losangeles" "philadelphia" 3846)
           ("losangeles" "westpalm" 3731) 
           ("losangeles" "roanoke" 3460) 
           ("memphis" "baltimore" 1269)
           ("memphis" "denver" 1422)
           ("memphis" "miami" 1396)
           ("memphis" "stlouis" 391)
           ("memphis" "newark" 1518)
           ("memphis" "boston" 1823)
           ("memphis" "philadelphia" 1406)
           ("memphis" "westpalm" 1326) 
           ("memphis" "roanoke" 932) 
           ("roanoke" "baltimore" 365)
           ("roanoke" "denver" 2191)
           ("roanoke" "miami" 1283)
           ("roanoke" "stlouis" 917)
           ("roanoke" "newark" 628)
           ("roanoke" "boston" 945)
           ("roanoke" "philadelphia" 506)
           ("roanoke" "westpalm" 1175) 
           ("newark" "westpalm" 1600)
           ("denver" "miami" 2776)
           ("miami" "stlouis" 1712)
           ("denver" "stlouis" 1275)
           ("philadelphia" "stlouis" 1304)
           ("miami" "philadelphia" 1645)
           ("philadelphia" "denver" 2534)
           ("philadelphia" "newark" 263)
           ("stlouis" "newark" 1396)
           ("denver" "newark" 2607)
           ("miami" "newark" 1758)
           ("westpalm" "miami" 108)
           ("westpalm" "philadelphia" 1500)
           ("westpalm" "baltimore" 1434)
           ("westpalm" "denver" 2720)
           ("westpalm" "stlouis" 1629)
           ("boston" "denver" 2844)
           ("boston" "stlouis" 1674)
           ("boston" "miami" 2029)
           ("boston" "philadelphia" 440)
           ("boston" "baltimore" 580)
           ("boston" "westpalm" 1923)
           ("boston" "newark" 316)
           ("philadelphia" "baltimore" 200)
           ("baltimore" "newark" 275)
           ("baltimore" "denver" 2426)
           ("baltimore" "stlouis" 1181)
           ("baltimore" "miami" 1543)))
        (carriers
          '(
            (fly "bangor" "ithaca")
            (take-bus "philadelphia" "ithaca")
            (take-bus "miami" "westpalm")
            (fly "boston" "losangeles")
            (fly "roanoke" "memphis")
            (take-train "memphis" "stlouis")
            (take-bus "roanoke" "miami")
            (fly "miami" "philadelphia")
            (take-train "miami" "stlouis")
            (fly "miami" "ithaca")
            (fly "denver" "miami")
            (fly "boston" "bangor")
            (fly "westpalm" "baltimore")
            (fly "baltimore" "philadelphia")
            (fly "philadelphia" "newark")
            (fly "newark" "boston")
            (fly "westpalm" "pittsburgh")
            (fly "pittsburgh" "philadelphia")
            (fly "denver" "stlouis")
            (fly "denver" "baltimore")
            (fly "stlouis" "boston")
            (fly "miami" "boston")
            (take-train "boston" "westpalm")
            (fly "miami" "stlouis")
            (fly "stlouis" "philadelphia")
            (fly "philadelphia" "stlouis")
            (take-bus "denver" "miami")
            (take-bus "denver" "boston")
            (take-bus "philadelphia" "baltimore")
            (fly "philadelphia" "baltimore")
            (fly "baltimore" "miami")
            (take-bus "philadelphia" "newark"))))
     (assign-properties distance carriers)))

